"use client";
import Link from "next/link";
import {Eye,Newspaper,Users,FolderOpen,ArrowUpRight} from "lucide-react";
import {useResource} from "../../lib/use-resource";
import {PageHeading,Notice,Loading,Empty,Badge} from "../../components/ui";
export default function Analytics(){
 const {data,loading,error,reload}=useResource("/admin/dashboard");
 return <><PageHeading eyebrow="UNDERSTAND YOUR PUBLICATION" title="Content insights" description="Real article activity, with a clearer view of what’s being read." actions={<button className="btn" onClick={reload}>Refresh insights</button>}/><Notice>{error}</Notice>{loading?<Loading/>:<><div className="stats-grid">{[["totalViews","Article views",Eye],["totalArticles","Total stories",Newspaper],["totalAuthors","Authors",Users],["totalCategories","Categories",FolderOpen]].map(([key,label,Icon])=><div className="stat-card" key={key}><div className="stat-top">{label}<span className="stat-icon"><Icon size={18}/></span></div><div className="stat-value">{new Intl.NumberFormat("en-IN").format(data?.[key]||0)}</div><span className="stat-note">Current publication totals</span></div>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>Most-read stories</h2><p>Ranked by recorded article views</p></div></div>{data?.topArticles?.length?<div className="table-wrap"><table><thead><tr><th>Story</th><th>Status</th><th>Views</th><th/></tr></thead><tbody>{data.topArticles.map(a=><tr key={a._id}><td>{a.title}</td><td><Badge status={a.status}/></td><td>{a.analytics?.views||0}</td><td><Link className="icon-button" href={`/articles/${a._id}/edit`} aria-label={`Open ${a.title}`}><ArrowUpRight size={15}/></Link></td></tr>)}</tbody></table></div>:<Empty title="Every reader starts with a story" description="Publish an article to start seeing readership here."/>}</section><section className="panel"><div className="panel-head"><h2>Your content mix</h2></div><div className="panel-body">{["published","draft","scheduled","archived","deleted"].map(s=><div className="bar-row" key={s}><span style={{textTransform:"capitalize"}}>{s}</span><div className="bar-track"><div className="bar-fill" style={{width:`${data?.totalArticles?(data[s+"Articles"]||0)/data.totalArticles*100:0}%`}}/></div><strong>{data?.[s+"Articles"]||0}</strong></div>)}<p className="muted" style={{fontSize:11,marginTop:25}}>Views count article visits, not unique people. No estimated reach or growth is shown.</p></div></section></div></>}</>;
}

