"use client";
import {useState} from "react";
import {Plus,ShieldCheck,ArrowUpRight} from "lucide-react";
import {useAuth} from "../../components/auth-provider";
import {useResource} from "../../lib/use-resource";
import {apiPost,siteUrl} from "../../lib/api";
import {PageHeading,Notice,Modal,Field,Loading} from "../../components/ui";
function Team(){
 const {data,loading,error,reload}=useResource("/auth/admins");const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[problem,setProblem]=useState("");
 const submit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setProblem("");try{await apiPost("/auth/admins",values);setOpen(false);reload();}catch(e){setProblem(e.message);}finally{setBusy(false);}};
 return <section className="panel" style={{marginTop:22}}><div className="panel-head"><h2>Workspace team</h2><button className="btn small" onClick={()=>setOpen(true)}><Plus size={14}/>Add team member</button></div><Notice>{error}</Notice>{loading?<Loading/>:<div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{data?.map(a=><tr key={a._id}><td>{a.name}</td><td>{a.email}</td><td style={{textTransform:"capitalize"}}>{a.role}</td><td>{a.isActive?"Active":"Inactive"}</td></tr>)}</tbody></table></div>}{open&&<Modal title="Add a team member" onClose={()=>!busy&&setOpen(false)}><form onSubmit={submit}><Notice>{problem}</Notice><Field label="Full name"><input name="name" required/></Field><Field label="Email"><input name="email" type="email" required autoComplete="off"/></Field><Field label="Initial password" hint="At least 12 characters; no more than 72 UTF-8 bytes."><input name="password" type="password" minLength={12} required autoComplete="new-password"/></Field><Field label="Role"><select name="role"><option value="author">Author</option><option value="editor">Editor</option><option value="admin">Admin</option><option value="superadmin">Superadmin</option></select></Field><button className="btn primary" disabled={busy}>{busy?"Creating…":"Create account"}</button></form></Modal>}</section>;
}
export default function Settings(){
 const {admin}=useAuth();const {data,loading,error,reload}=useResource("/health");
 return <><PageHeading eyebrow="YOUR WORKSPACE" title="Settings" description="Account details, publication connections, and your team."/><div className="settings-grid"><section className="panel"><div className="panel-head"><h2>Your account</h2><ShieldCheck size={19} className="muted"/></div><div className="panel-body"><dl>{[["Name",admin.name],["Email",admin.email],["Role",admin.role]].map(([label,value])=><div key={label} className="data-row"><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="muted" style={{fontSize:11,marginTop:20}}>Permissions are enforced by the API for every request.</p></div></section><section className="panel"><div className="panel-head"><h2>Publication connection</h2><button className="btn small" onClick={reload}>Check status</button></div><div className="panel-body"><Notice>{error}</Notice><dl><div className="data-row"><dt>Website</dt><dd><a href={siteUrl} className="text-link" target="_blank" rel="noreferrer">Open TrendsDuniya <ArrowUpRight size={13}/></a></dd></div><div className="data-row"><dt>CMS API</dt><dd>{loading?"Checking…":error?"Unavailable":"Connected"}</dd></div><div className="data-row"><dt>Database</dt><dd>{data?.database||"Unknown"}</dd></div></dl><p className="muted" style={{fontSize:11,marginTop:20}}>Your session is stored in secure, HTTP-only cookies.</p></div></section></div>{admin.role==="superadmin"&&<Team/>}</>;
}

