import Link from 'next/link';
import TopicCard from '@/components/TopicCard';
import StoryBrowser from '@/components/StoryBrowser';
import { latestTopics,dateLabel } from '@/lib/topics';
import { summaries } from '@/lib/summaries';
import { JsonLd,pageMetadata } from '@/lib/seo';
import { siteConfig } from '@/config/site';
export const metadata={...pageMetadata('Latest Trending News in Hindi & English','Today’s stories, carefully explained. Read Hindi and English coverage of India, sports, technology, education and more.','/'),title:{absolute:'TrendsDuniya - Latest Trending News in Hindi & English'}};
export default function Home(){const topics=latestTopics();const featured=topics.filter(t=>t.featured).slice(0,3);const picks=featured.length?featured:topics.slice(0,3);return <div className="container home"><div className="edition-line"><span>THE DAILY EDITION</span><time dateTime={topics[0]?.updatedAt}>{topics[0]&&dateLabel(topics[0].updatedAt)}</time><span>HINDI + ENGLISH</span></div><section className="hero"><p className="eyebrow">BEYOND THE HEADLINE</p><h1><span lang="hi">आज क्या ट्रेंड कर रहा है?</span> <span className="hero-divider">|</span> <span>What&apos;s Trending Today</span></h1><p lang="hi">आज की चर्चित खबरें, trending topics और आसान explainers — Hindi और English में.</p></section><section className="top-stories"><div className="section-heading"><h2>Top Stories</h2><Link href="/latest">The latest edition ↗</Link></div><div className="top-grid">{picks.map((t,i)=><TopicCard topic={t} key={t.slug} lead={i===0}/>)}</div></section><div className="editorial-strip"><span className="strip-mark">TD /</span><div><strong>A little more context. A better understanding.</strong><p>Original explainers, named sources and a clear distinction between what is known and what is still developing.</p></div><Link href="/editorial-policy">Our editorial approach ↗</Link></div><section><div className="section-heading"><h2>Trending Now</h2><span>Stories worth your time</span></div><StoryBrowser stories={summaries(topics)}/></section>{[['Sports','Latest in Sports'],['Entertainment','Latest in Entertainment'],['Technology','Technology'],['India','India']].map(([category,title])=>{const items=topics.filter(t=>t.category===category).slice(0,3);return items.length>0&&<section key={category}><div className="section-heading"><h2>{title}</h2><Link href={`/category/${category.toLowerCase()}`}>View all ↗</Link></div><div className="story-grid">{items.map(t=><TopicCard topic={t} key={t.slug}/>)}</div></section>})}<div className="language-columns">{(['hi','en'] as const).map(lang=><section key={lang}><div className="section-heading"><h2>{lang==='hi'?'Hindi Stories / हिन्दी':'English Stories'}</h2></div>{topics.filter(t=>t.language===lang).slice(0,3).map(t=><TopicCard key={t.slug} topic={t}/>)}</section>)}</div><JsonLd data={{'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':`${siteConfig.url}/#website`,url:siteConfig.url,name:siteConfig.name,inLanguage:['en','hi']},{'@type':'Organization','@id':`${siteConfig.url}/#organization`,name:siteConfig.name,url:siteConfig.url}]}}/></div>;}
