import { Router } from "express";
import { authenticate } from "../middleware/auth.middleware.js";
import { allowRoles } from "../middleware/admin.middleware.js";
import { durableLimit } from "../middleware/aiRateLimit.middleware.js";
import env from "../config/env.js";
import * as c from "../controllers/ai.controller.js";
const router=Router();
router.use(authenticate,allowRoles("superadmin","admin","editor"));
router.use((req,res,next)=>{res.set("Cache-Control","no-store");next();});
router.get("/readiness",c.readiness);
router.get("/status",durableLimit("ai-test",10),c.status);
router.post("/generate-article",durableLimit("ai-generation",env.aiGenerationLimit),c.generate);
export default router;
