import {Router} from "express";
import * as c from "../controllers/article.controller.js";
import {authenticate} from "../middleware/auth.middleware.js";
import {allowRoles} from "../middleware/admin.middleware.js";
import {articleValidator} from "../validators/article.validator.js";
import {publicRateLimit} from "../middleware/rateLimit.middleware.js";
import {rateLimit} from "express-rate-limit";
import Category from "../models/Category.js";import Tag from "../models/Tag.js";import Author from "../models/Author.js";
const router=Router();
router.get("/search",publicRateLimit,c.search);
router.get("/category/:slug",publicRateLimit,c.getArticlesByTaxonomy("category",Category));
router.get("/tag/:slug",publicRateLimit,c.getArticlesByTaxonomy("tag",Tag));
router.get("/author/:slug",publicRateLimit,c.getArticlesByTaxonomy("author",Author));
router.get("/",publicRateLimit,c.listArticles);
router.get("/:slug/related",publicRateLimit,c.getRelatedArticles);
router.get("/:slug",publicRateLimit,c.getPublicArticle);
router.post("/:id/view",rateLimit({windowMs:60000,limit:15,standardHeaders:"draft-8",legacyHeaders:false}),c.view);
export const adminRouter=Router();adminRouter.use(authenticate);
adminRouter.get("/",c.adminArticles);adminRouter.get("/:id",c.getAdminArticle);
adminRouter.post("/",articleValidator,c.createArticle);
adminRouter.put("/:id",articleValidator,c.updateArticle);adminRouter.patch("/:id",articleValidator,c.updateArticle);
adminRouter.delete("/:id",allowRoles("superadmin","admin"),c.softDelete);
adminRouter.post("/:id/publish",allowRoles("superadmin","admin","editor"),c.publishArticle);
adminRouter.post("/:id/unpublish",allowRoles("superadmin","admin","editor"),c.changeStatus("draft","UNPUBLISH"));
adminRouter.post("/:id/archive",allowRoles("superadmin","admin","editor"),c.changeStatus("archived","ARCHIVE"));
adminRouter.post("/:id/restore",allowRoles("superadmin"),c.restore);
adminRouter.delete("/:id/permanent",allowRoles("superadmin"),c.permanentDelete);
adminRouter.post("/:id/duplicate",c.duplicate);
adminRouter.get("/:id/revisions",c.revisions);adminRouter.get("/:id/revisions/:revisionId",c.getRevision);adminRouter.post("/:id/revisions/:revisionId/restore",allowRoles("superadmin","admin","editor"),c.restoreRevision);
adminRouter.get("/:id/preview",c.getAdminArticle);adminRouter.post("/:id/preview",c.getAdminArticle);
export default router;

