"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
import {LayoutDashboard,Newspaper,FolderOpen,Tags,Users,ChartNoAxesCombined,Settings2,LogOut,ArrowUpRight,Plus,Menu,X,Search,PanelLeftClose,Globe2,TrendingUp,BrainCircuit} from "lucide-react";
import {useAuth} from "./auth-provider";
import {siteUrl} from "../lib/api";
import {Notice} from "./ui";
const links=[["Overview","/",LayoutDashboard],["Articles","/articles",Newspaper],["Categories","/categories",FolderOpen],["Tags","/tags",Tags],["Authors","/authors",Users],["Analytics","/analytics",ChartNoAxesCombined],["Trending Topics","/trending",TrendingUp],["AI Status","/setup-ai",BrainCircuit],["Settings","/settings",Settings2]];
export default function AdminShell({children}){
 const path=usePathname(),{admin,logout}=useAuth();const [open,setOpen]=useState(false),[error,setError]=useState("");
 if(path==="/login")return children;
 if(!admin)return null;
 return <div className="admin-shell"><a href="#main-content" className="skip-link">Skip to content</a>{open&&<button className="sidebar-scrim" onClick={()=>setOpen(false)} aria-label="Close navigation"/>}<aside className={`sidebar ${open?"open":""}`}><Link href="/" className="brand"><span className="brand-mark"><Globe2 size={23}/></span><span>Trends<span className="brand-accent">Duniya</span><small>EDITORIAL STUDIO</small></span></Link><button className="mobile-close icon-button" onClick={()=>setOpen(false)} aria-label="Close menu"><X size={20}/></button><div className="workspace-label"><span className="workspace-avatar">TD</span><div>TrendsDuniya<small>Publishing workspace</small></div><PanelLeftClose size={15}/></div><p className="nav-label">WORKSPACE</p><nav>{links.map(([name,href,Icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} className={path===href||href!=="/"&&path.startsWith(href)?"active":""}><Icon size={18}/>{name}{name==="Articles"&&<span className="nav-shortcut">↗</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="sidebar-callout"><span className="live-dot"/> Your stories. A wider world.<p>Make your next story count.</p><a href={siteUrl} target="_blank" rel="noreferrer">Visit website <ArrowUpRight size={15}/></a></div><button className="profile-button" onClick={async()=>{try{await logout();}catch(e){setError(e.message);}}}><span className="avatar">{admin.name?.slice(0,2).toUpperCase()}</span><span>{admin.name}<small>{admin.role}</small></span><LogOut size={17}/></button></div></aside><div className="workspace-main"><header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={22}/></button><span className="topbar-title">Your editorial workspace</span></div><form action="/articles" className="topbar-search"><Search size={16}/><input name="search" placeholder="Find an article…" aria-label="Find an article"/><kbd>↵</kbd></form><div className="topbar-actions"><a href={siteUrl} target="_blank" rel="noreferrer" className="website-link">View website <ArrowUpRight size={15}/></a><Link href="/articles/new" className="btn primary small"><Plus size={16}/>New article</Link></div></header><main id="main-content" className="workspace-content">{error&&<Notice>{error}</Notice>}{children}</main><footer className="admin-footer"><span>TrendsDuniya Studio</span><span>Made for stories that matter.</span></footer></div></div>;
}

